/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 bwscroll.glb 
Author: Shahriar Shahrabi (https://sketchfab.com/shahriyarshahrabi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mountain-and-river-scroll-black-and-white-1dbff009f52f4f6b8f569be1a1e15c63
Title: Mountain And River Scroll - Black and White
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BwScroll(props) {
  const { nodes, materials } = useGLTF('/assets/Scroll/bwscroll.glb')
  const ref = useRef();

  return (
    <group {...props} dispose={null}>
      <group scale={0.012} position={[ -10, -11, -180]} rotation={[-Math.PI / 2, 0, 5]}>
        <group scale={100}>
          <mesh geometry={nodes.Base_SketchfabMat_0.geometry} material={materials.SketchfabMat} />
          <mesh geometry={nodes.Base_SketchfabMat_0_1.geometry} material={materials.SketchfabMat} />
        </group>
        <group  scale={100}>
          <mesh geometry={nodes.Trees_VertexColor_0.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_1.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_2.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_3.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_4.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_5.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_6.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_7.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_8.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_9.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_10.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_11.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_12.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_13.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_14.geometry} material={materials.VertexColor} />
        </group>
        <mesh geometry={nodes.Outline_VertexColor_0.geometry} material={materials.VertexColor}  scale={100} />
        <mesh geometry={nodes.BrushStrokes001_BrushStrokes001_0.geometry} material={materials['BrushStrokes.001']} scale={100} />
        <mesh geometry={nodes.Rest_SketchfabMat_0.geometry} material={materials.SketchfabMat}  scale={100} />
      </group>
      <group scale={0.02} position={[ 85, -11, -190]} rotation={[-Math.PI / 2, 0, 13]}>
        <group scale={100}>
          <mesh geometry={nodes.Base_SketchfabMat_0.geometry} material={materials.SketchfabMat} />
          <mesh geometry={nodes.Base_SketchfabMat_0_1.geometry} material={materials.SketchfabMat} />
        </group>
        <group  scale={100}>
          <mesh geometry={nodes.Trees_VertexColor_0.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_1.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_2.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_3.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_4.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_5.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_6.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_7.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_8.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_9.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_10.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_11.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_12.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_13.geometry} material={materials.VertexColor} />
          <mesh geometry={nodes.Trees_VertexColor_0_14.geometry} material={materials.VertexColor} />
        </group>
        <mesh geometry={nodes.Outline_VertexColor_0.geometry} material={materials.VertexColor}  scale={100} />
        <mesh geometry={nodes.BrushStrokes001_BrushStrokes001_0.geometry} material={materials['BrushStrokes.001']} scale={100} />
        <mesh geometry={nodes.Rest_SketchfabMat_0.geometry} material={materials.SketchfabMat}  scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/Scroll/bwscroll.glb')
