/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 butterfly1.glb 
Author: vmmaniac (https://sketchfab.com/vmmaniac)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-flying-fluttering-butterfly-loop-c2b6e9655f8e42e3b309cbedee91c5d3
Title: Animated Flying Fluttering Butterfly Loop
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Butterfly1(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/assets/butterfly/butterfly1.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(()=> {
    actions.take_off_and_land.play()
  },[actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene" position={[21.205, 55.192, 34.777]} scale={35}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_159" scale={0.01}>
                <group name="skeletal3_158">
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group name="butterfly2_157" />
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.001']} skeleton={nodes.Object_8.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/butterfly/butterfly1.glb')
